#define SECRET_CH_ID INSERT OWN VALUES
#define SECRET_WRITE_APIKEY "INSERT OWN VALUES"
#define INTERVAL 15000
#define WIFI_NAME "INSERT OWN VALUES"    
#define WIFI_PASSWORD "INSERT OWN VALUES"
#define DATABASE_URL "INSERT OWN VALUES"
#define DATABASE_SECRET "INSERT OWN VALUES"